# Generated by Django 5.2.8 on 2025-12-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
